PROG = src.cpp
TARGET = proj
LIBRARY = /Users/suzukiyuuya/Github/atcoder/library
CXX = g++
CXX_VERSION = -std=c++17

${TARGET} : ${PROG}
	${CXX} ${CXX_VERSION} -o ${TARGET} -I${LIBRARY} ${PROG}

run :
	./proj

clean :
	rm -r ${TARGET}
